### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by stepancar** [guitarrapc/git-shallow-clone-orb#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Orb version

2.4.1

### Current behavior

I started getting such message 

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@       WARNING: POSSIBLE DNS SPOOFING DETECTED!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The RSA host key for github.com has changed,
and the key for the corresponding IP address 140.82.113.4
is unknown. This could either mean that
DNS SPOOFING is happening or the IP address for the host
and its host key have changed at the same time.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
```

Switching to regular circle ci checkout it's gone

### Minimum reproduction config

```
orbs:
    docker: circleci/docker@1.5.0
    slack: circleci/slack@4.1
    git-shallow-clone: guitarrapc/git-shallow-clone@2.4.1
jobs:
    lint:
        working_directory: ~/repo
        steps:
            - git-shallow-clone/checkout:
                  depth: 1
```

### Other

no
