### ISSUE TITLE
Cannot find a definition for job named git/checkout_shallow

### ISSUE THREAD

**Issue by dlime** [guitarrapc/git-shallow-clone-orb#8]
I tried the example but unfortunately keep getting an error:

```
version: 2.1

orbs:
  git: guitarrapc/git-shallow-clone@0.2.0

workflows:
  build:
    jobs:
      - git/checkout_shallow
```

```
Error calling workflow: build
Cannot find a definition for job named git/checkout_shallow
```
